title: Data Science for all
description: >-
  This course is designed for anyone who want to build a career into the most demanding job of the century i.e., Data Science, irrespective of their background. Course has been tailor made as per the learners needs because we know their problems, the "best"!!
template:
  repo: data-science-for-all-template
  name: data-science-for-all
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
